### PR TITLE
Unify errors under a single PusherPlatform::Error class

### PR DESCRIPTION
**Pull request by hamchapman**
### What?

See title

### Why?

Make it straightforward for users of the SDK to rescue all errors being raised by this SDK so that they can do things like namespace however they like, for example.

----

- [x] README updated if you changed the API?
- [x] CHANGELOG updated if relevant?

----

CC @pusher/sigsdk

### CODE REVIEW

**Comment by BenPope** [comment]
Looks consistent, aside from capitalisation. @vivangkumar ?

**Comment by hamchapman** [comment]
What capitalisation?

**Comment by BenPope** [comment]
In the error strings returned.

**Comment by vivangkumar** [comment]
Does look good. Although we don't currently return errors in the platform-go library for these checks. Perhaps we should?

**Comment by hamchapman** [comment]
What do you do there instead?

**Pull request merged**
